# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-US"
title                    : "Junyue Jiang's Academic Portfolio"
title_separator          : "|"
name                     : &name "Junyue Jiang"
description              : &description "Junyue Jiang - Computer Engineering Scholar"
url                      : "https://junyuejiang.github.io" # Replace with your custom domain if you have one
baseurl                  : "" 
repository               : "junyuejiang/junyuejiang.github.io" # Replace with your GitHub username and repo
teaser                   : "teaser-image.png" # Replace with your own teaser image in /images/
breadcrumbs              : true
words_per_minute         : 200
future                   : true
read_more                : "enabled"
talkmap_link             : true
comments:
  provider               : "disqus" # Choose your preferred comments provider
  disqus:
    shortname            : "junyuejiang-disqus" # Replace with your Disqus shortname

# SEO Related
google_site_verification : # Add your Google verification code if available
bing_site_verification   : 
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter "junyuejiang" # Your Twitter handle
facebook:
  username               : # Your Facebook profile ID
og_image                 : "social-share.png" # Default Open Graph/Twitter share image

# Analytics
analytics:
  provider               : "google-universal"
  google:
    tracking_id          : # Your Google Analytics tracking ID

# Site Author
author:
  name             : "Junyue Jiang"
  avatar           : "junyuejiang-avatar.png" # Replace with your own avatar image
  bio              : "Exploring the intersection of Computer Engineering and AI."
  location         : "Urbana-Champaign"
  email            : "junyuej2@illinois.edu"
  linkedin         : "junyue-jiang-52454222b"
  googlescholar    : "http://yourgooglescholarurl.com" # Replace with your full Google Scholar URL
  researchgate     : "https://www.researchgate.net/profile/Junyue_Jiang" # Replace with your ResearchGate profile
  github           : "junyuejiang" # Your GitHub username

# Collections (adjust according to the content you want to present)
collections:
  research:
    output: true
    permalink: /research/:path/
  publications:
    output: true
    permalink: /publications/:path/
  projects:
    output: true
    permalink: /projects/:path/
  talks:
    output: true
    permalink: /talks/:path/



# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: America/Los_Angeles # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
